name: Trigger auto deployment for safe-settings

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main-enterprise ]
    paths:
    - '**'
    - '.github/workflows/safe-settings-AutoDeployTrigger-3a97c27d-d9fa-4a87-9344-d4aadab5a4df.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SAFESETTINGS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SAFESETTINGS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SAFESETTINGS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: safesettingsreg.azurecr.io
          registryUsername: ${{ secrets.SAFESETTINGS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SAFESETTINGS_REGISTRY_PASSWORD }}
          containerAppName: safe-settings
          resourceGroup: safesettings-demo-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


